version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.9.0

    working_directory: ~/trello-case-study

    steps:
      - checkout
      - restore_cache:
          key: node_modules-cache-{{ checksum package.json }}
      - run: yarn install
      - save_cache:
          key: node_modules-cache-{{ checksum package.json }}
          paths:
            - node_modules
      - run: yarn test
      - run: yarn build
  deploy:
    docker:
      - image: buildpack-deps:trusty
    steps:
      - checkout
      - run:
          name: Deploy to Heroku
          command: |
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
